# Setup
title:        harrywantstodev
tagline:      Jailbroken iOS Development
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       harrywantstodev
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown