# Setup
title:        harrywantstodev
tagline:      Jailbroken iOS Development
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:        
  url:        http://harrywantstodev.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown